-- MySQL Script generated by MySQL Workbench
-- Fri Oct 14 03:00:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema noon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema noon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `noon` DEFAULT CHARACTER SET utf8mb3 ;
USE `noon` ;

-- -----------------------------------------------------
-- Table `noon`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noon`.`member` (
  `id` VARCHAR(30) NOT NULL,
  `pw` VARCHAR(30) NULL DEFAULT NULL,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  `initdate` DATE NULL DEFAULT NULL,
  `updatedate` DATE NULL DEFAULT NULL,
  `deletedate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `noon`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noon`.`menu` (
  `name` VARCHAR(30) NOT NULL,
  `category` VARCHAR(45) NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `photo` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `noon`.`setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noon`.`setting` (
  `setno` INT NOT NULL AUTO_INCREMENT,
  `initdate` DATE NULL DEFAULT NULL,
  `enddate` DATE NULL DEFAULT NULL,
  `pricenow` INT NULL DEFAULT NULL,
  `photonow` MEDIUMBLOB NULL DEFAULT NULL,
  `menu_name` VARCHAR(30) NOT NULL,
  `shop_shopcode` INT NOT NULL,
  `categorynow` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`setno`, `menu_name`, `shop_shopcode`),
  UNIQUE INDEX `setno_UNIQUE` (`setno` ASC) VISIBLE,
  INDEX `fk_set_menu1_idx` (`menu_name` ASC) VISIBLE,
  INDEX `fk_set_shop1_idx` (`shop_shopcode` ASC) VISIBLE,
  CONSTRAINT `fk_setting_menu1`
    FOREIGN KEY (`menu_name`)
    REFERENCES `noon`.`menu` (`name`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `noon`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noon`.`shop` (
  `shopcode` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `province` VARCHAR(20) NULL DEFAULT NULL,
  `city` VARCHAR(20) NULL DEFAULT NULL,
  `town` VARCHAR(20) NULL DEFAULT NULL,
  `village` VARCHAR(20) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `opentime` TIME NULL DEFAULT NULL,
  `closetime` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`shopcode`),
  UNIQUE INDEX `shopcode_UNIQUE` (`shopcode` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `noon`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noon`.`staff` (
  `id` VARCHAR(30) NOT NULL,
  `pw` VARCHAR(30) NULL DEFAULT NULL,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `debitno` VARCHAR(45) NULL DEFAULT NULL,
  `photo` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `noon`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noon`.`order` (
  `orderno` INT NOT NULL AUTO_INCREMENT,
  `ordertime` DATETIME NULL DEFAULT NULL,
  `refundtime` DATETIME NULL DEFAULT NULL,
  `hotice` TINYINT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `forheretogo` VARCHAR(30) NULL DEFAULT NULL,
  `shot` INT NULL DEFAULT NULL,
  `syrup` INT NULL DEFAULT NULL,
  `size` INT NULL DEFAULT NULL,
  `indiprice` INT NULL DEFAULT NULL,
  `customerno` INT NULL DEFAULT NULL,
  `member_id` VARCHAR(30) NOT NULL,
  `set_setno` INT NOT NULL,
  `set_menu_name` VARCHAR(30) NOT NULL,
  `shop_shopcode` INT NOT NULL,
  `staff_id` VARCHAR(30) NOT NULL,
  `paytime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`orderno`, `member_id`, `set_setno`, `set_menu_name`, `shop_shopcode`, `staff_id`),
  UNIQUE INDEX `no_UNIQUE` (`orderno` ASC) VISIBLE,
  INDEX `fk_order_member1_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_order_set1_idx` (`set_setno` ASC, `set_menu_name` ASC) VISIBLE,
  INDEX `fk_order_shop1_idx` (`shop_shopcode` ASC) VISIBLE,
  INDEX `fk_order_staff1_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `noon`.`member` (`id`),
  CONSTRAINT `fk_order_set1`
    FOREIGN KEY (`set_setno` , `set_menu_name`)
    REFERENCES `noon`.`setting` (`setno` , `menu_name`),
  CONSTRAINT `fk_order_shop1`
    FOREIGN KEY (`shop_shopcode`)
    REFERENCES `noon`.`shop` (`shopcode`),
  CONSTRAINT `fk_order_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `noon`.`staff` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `noon`.`complete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noon`.`complete` (
  `completeno` INT NOT NULL AUTO_INCREMENT,
  `completetime` DATETIME NULL DEFAULT NULL,
  `accepttime` DATETIME NULL DEFAULT NULL,
  `staff_id` VARCHAR(30) NOT NULL,
  `shop_shopcode` INT NOT NULL,
  `order_orderno` INT NOT NULL,
  `order_member_id` VARCHAR(30) NOT NULL,
  `order_set_setno` INT NOT NULL,
  `order_set_menu_name` VARCHAR(30) NOT NULL,
  `order_shop_shopcode` INT NOT NULL,
  PRIMARY KEY (`completeno`, `staff_id`, `shop_shopcode`, `order_orderno`, `order_member_id`, `order_set_setno`, `order_set_menu_name`, `order_shop_shopcode`),
  UNIQUE INDEX `no_UNIQUE` (`completeno` ASC) VISIBLE,
  INDEX `fk_complete_staff1_idx` (`staff_id` ASC) VISIBLE,
  INDEX `fk_complete_shop1_idx` (`shop_shopcode` ASC) VISIBLE,
  INDEX `fk_complete_order1_idx` (`order_orderno` ASC, `order_member_id` ASC, `order_set_setno` ASC, `order_set_menu_name` ASC, `order_shop_shopcode` ASC) VISIBLE,
  CONSTRAINT `fk_complete_order1`
    FOREIGN KEY (`order_orderno` , `order_member_id` , `order_set_setno` , `order_set_menu_name` , `order_shop_shopcode`)
    REFERENCES `noon`.`order` (`orderno` , `member_id` , `set_setno` , `set_menu_name` , `shop_shopcode`),
  CONSTRAINT `fk_complete_shop1`
    FOREIGN KEY (`shop_shopcode`)
    REFERENCES `noon`.`shop` (`shopcode`),
  CONSTRAINT `fk_complete_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `noon`.`staff` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `noon`.`executive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noon`.`executive` (
  `id` VARCHAR(30) NOT NULL,
  `pw` VARCHAR(30) NULL DEFAULT NULL,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `employeeno` INT NULL DEFAULT NULL,
  `photo` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `noon`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noon`.`manager` (
  `id` VARCHAR(30) NOT NULL,
  `pw` VARCHAR(30) NULL DEFAULT NULL,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `employeeno` INT NULL DEFAULT NULL,
  `photo` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `noon`.`hire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noon`.`hire` (
  `hireno` INT NOT NULL AUTO_INCREMENT,
  `updatedate` DATE NULL DEFAULT NULL,
  `registerdate` DATE NULL DEFAULT NULL,
  `deletedate` DATE NULL DEFAULT NULL,
  `shop_shopcode` INT NOT NULL,
  `staff_id` VARCHAR(30) NOT NULL,
  `manager_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`hireno`, `shop_shopcode`, `staff_id`, `manager_id`),
  UNIQUE INDEX `registerno_UNIQUE` (`hireno` ASC) VISIBLE,
  INDEX `fk_register_shop1_idx` (`shop_shopcode` ASC) VISIBLE,
  INDEX `fk_register_staff1_idx` (`staff_id` ASC) VISIBLE,
  INDEX `fk_hire_manager1_idx` (`manager_id` ASC) VISIBLE,
  CONSTRAINT `fk_hire_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `noon`.`manager` (`id`),
  CONSTRAINT `fk_register_shop1`
    FOREIGN KEY (`shop_shopcode`)
    REFERENCES `noon`.`shop` (`shopcode`),
  CONSTRAINT `fk_register_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `noon`.`staff` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `noon`.`manage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noon`.`manage` (
  `manageno` INT NOT NULL AUTO_INCREMENT,
  `startdate` DATE NULL DEFAULT NULL,
  `enddate` DATE NULL DEFAULT NULL,
  `shop_shopcode` INT NOT NULL,
  `manager_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`manageno`, `shop_shopcode`, `manager_id`),
  UNIQUE INDEX `manageno_UNIQUE` (`manageno` ASC) VISIBLE,
  INDEX `fk_manage_shop1_idx` (`shop_shopcode` ASC) VISIBLE,
  INDEX `fk_manage_manager1_idx` (`manager_id` ASC) VISIBLE,
  CONSTRAINT `fk_manage_manager1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `noon`.`manager` (`id`),
  CONSTRAINT `fk_manage_shop1`
    FOREIGN KEY (`shop_shopcode`)
    REFERENCES `noon`.`shop` (`shopcode`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `noon`.`point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noon`.`point` (
  `pointno` INT NOT NULL AUTO_INCREMENT,
  `pointdate` DATE NULL DEFAULT NULL,
  `pointcash` INT NULL DEFAULT NULL,
  `member_id` VARCHAR(30) NOT NULL,
  `order_orderno` INT NOT NULL,
  `order_member_id` VARCHAR(30) NOT NULL,
  `order_set_setno` INT NOT NULL,
  `order_set_menu_name` VARCHAR(30) NOT NULL,
  `order_shop_shopcode` INT NOT NULL,
  `order_staff_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`pointno`, `member_id`, `order_orderno`, `order_member_id`, `order_set_setno`, `order_set_menu_name`, `order_shop_shopcode`, `order_staff_id`),
  UNIQUE INDEX `pointno_UNIQUE` (`pointno` ASC) VISIBLE,
  INDEX `fk_point_member_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_point_order1_idx` (`order_orderno` ASC, `order_member_id` ASC, `order_set_setno` ASC, `order_set_menu_name` ASC, `order_shop_shopcode` ASC, `order_staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_point_member`
    FOREIGN KEY (`member_id`)
    REFERENCES `noon`.`member` (`id`),
  CONSTRAINT `fk_point_order1`
    FOREIGN KEY (`order_orderno` , `order_member_id` , `order_set_setno` , `order_set_menu_name` , `order_shop_shopcode` , `order_staff_id`)
    REFERENCES `noon`.`order` (`orderno` , `member_id` , `set_setno` , `set_menu_name` , `shop_shopcode` , `staff_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `noon`.`shopregister`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `noon`.`shopregister` (
  `shopregisterno` INT NOT NULL AUTO_INCREMENT,
  `registerdate` DATE NULL DEFAULT NULL,
  `updatedate` DATE NULL DEFAULT NULL,
  `deletedate` DATE NULL DEFAULT NULL,
  `shop_shopcode` INT NOT NULL,
  `executive_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`shopregisterno`, `shop_shopcode`, `executive_id`),
  UNIQUE INDEX `shopregisterno_UNIQUE` (`shopregisterno` ASC) VISIBLE,
  INDEX `fk_shopregister_shop1_idx` (`shop_shopcode` ASC) VISIBLE,
  INDEX `fk_shopregister_executive1_idx` (`executive_id` ASC) VISIBLE,
  CONSTRAINT `fk_shopregister_executive1`
    FOREIGN KEY (`executive_id`)
    REFERENCES `noon`.`executive` (`id`),
  CONSTRAINT `fk_shopregister_shop1`
    FOREIGN KEY (`shop_shopcode`)
    REFERENCES `noon`.`shop` (`shopcode`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
